export interface VerticalMatrixEntry {
  id: string;
  laborLabel: string;
  disposalLabel: string;
  laborDesc: string;
  disposalDesc: string;
}

export const verticalMatrix: Record<string, VerticalMatrixEntry> = {
  asbestos_abatement: { id: 'asbestos_abatement', laborLabel: 'Asbestos Abatement Contractor', disposalLabel: 'Asbestos Disposal Facility', laborDesc: 'Asbestos remediation, lead paint abatement, hazmat containment, air monitoring', disposalDesc: 'Regulated asbestos waste transport, permitted hazmat landfill disposal' },
  dewatering: { id: 'dewatering', laborLabel: 'Dewatering Contractor', disposalLabel: 'Wastewater Treatment Plant', laborDesc: 'Construction dewatering, wellpoint systems, bypass pumping, groundwater control, trench dewatering', disposalDesc: 'Sediment basin discharge, filtration treatment, NPDES permitted outfall discharge' },
  elevator_inspection: { id: 'elevator_inspection', laborLabel: 'Elevator Repair Service', disposalLabel: 'Elevator & Lift Recycling', laborDesc: 'Elevator safety inspection, certification, load testing, ASME compliance', disposalDesc: 'Elevator modernization, obsolete equipment removal' },
  fire_sprinklers: { id: 'fire_sprinklers', laborLabel: 'Fire Protection Contractor', disposalLabel: 'Sprinkler System Recycling', laborDesc: 'Fire sprinkler hydrostatic testing, flow testing, NFPA 25 inspection', disposalDesc: 'Sprinkler system decommissioning, obsolete component recycling' },
  generator_testing: { id: 'generator_testing', laborLabel: 'Commercial Generator Service', disposalLabel: 'Waste Oil Recycling', laborDesc: 'Generator load bank testing, NFPA 110 compliance, emergency power testing', disposalDesc: 'Generator decommissioning, fuel polishing waste disposal, battery recycling' },
  hazardous_soil_remediation: { id: 'hazardous_soil_remediation', laborLabel: 'Soil Remediation Contractor', disposalLabel: 'Contaminated Soil Disposal', laborDesc: 'Soil excavation, contaminated soil removal, site remediation, bio-remediation', disposalDesc: 'Hazmat soil transport, TSCA/RCRA permitted landfill disposal, thermal treatment' },
  high_voltage_electrical: { id: 'high_voltage_electrical', laborLabel: 'High Voltage Electrical Contractor', disposalLabel: 'Copper & Metal Recycling', laborDesc: 'High voltage testing, transformer maintenance, switchgear testing, cable testing, NFPA 70E compliance', disposalDesc: 'PCB transformer disposal, SF6 recycling, decommissioned equipment recycling' },
  hvac_industrial: { id: 'hvac_industrial', laborLabel: 'Commercial HVAC Contractor', disposalLabel: 'Refrigerant Recovery Service', laborDesc: 'HVAC test and balance, air balancing, TAB services, airflow measurement', disposalDesc: 'HVAC equipment disposal, refrigerant recovery, ductwork removal' },
  hydro_excavation: { id: 'hydro_excavation', laborLabel: 'Hydro Excavation Service', disposalLabel: 'Liquid Waste Transfer Station', laborDesc: 'Hydro excavation, potholing, daylighting, utility exposure, non-destructive digging', disposalDesc: 'Spoils disposal, slurry containment, water management' },
  industrial_demolition: { id: 'industrial_demolition', laborLabel: 'Demolition Contractor', disposalLabel: 'C&D Recycling Center', laborDesc: 'Industrial demolition, concrete breaking, selective demolition, building implosion', disposalDesc: 'Demolition debris processing, concrete crushing, landfill disposal' },
  industrial_wastewater: { id: 'industrial_wastewater', laborLabel: 'Wastewater Treatment Service', disposalLabel: 'Industrial Waste Disposal', laborDesc: 'Industrial wastewater treatment, process water management, pH adjustment, filtration', disposalDesc: 'Treated effluent discharge, sludge dewatering, wastewater hauling' },
  marine_construction: { id: 'marine_construction', laborLabel: 'Marine Contractor', disposalLabel: 'Clean Fill Dump Site', laborDesc: 'Pile driving, seawall construction, bulkhead installation, dredging, dock building', disposalDesc: 'Dredge spoils disposal, marine debris management, sheet piling removal' },
  medical_waste: { id: 'medical_waste', laborLabel: 'Biohazard Cleanup Service', disposalLabel: 'Medical Waste Disposal', laborDesc: 'Medical waste collection, biohazard cleanup, sharps disposal, clinical waste pickup', disposalDesc: 'Autoclave sterilization, regulated medical waste incineration, treatment' },
  sandblasting: { id: 'sandblasting', laborLabel: 'Commercial Sandblasting Service', disposalLabel: 'Industrial Waste Facility', laborDesc: 'Abrasive blasting, sandblasting, surface preparation, industrial coating removal, lead paint abatement', disposalDesc: 'Spent abrasive disposal, hazardous media transport, EPA TCLP compliant disposal' },
  slurry_processing: { id: 'slurry_processing', laborLabel: 'Environmental Drilling Service', disposalLabel: 'Slurry & Liquid Waste Disposal', laborDesc: 'Concrete cutting, core drilling, saw cutting, concrete grinding, demolition', disposalDesc: 'Slurry dewatering/recycling, washout collection, filtration, filter press operations' },
  solar_infrastructure: { id: 'solar_infrastructure', laborLabel: 'Commercial Solar Contractor', disposalLabel: 'Solar Panel & E-Waste Recycling', laborDesc: 'Solar PV installation, commercial solar mounting, electrical integration, inverter commissioning', disposalDesc: 'Decommissioned panel recycling, inverter disposal, racking scrap metal recovery' },
  stormwater_compliance: { id: 'stormwater_compliance', laborLabel: 'Erosion Control Service', disposalLabel: 'Commercial Landfill', laborDesc: 'SWPPP development, stormwater inspections, compliance monitoring, erosion control', disposalDesc: 'Stormwater treatment, sediment basin cleaning, silt removal, erosion control installation' },
  tank_testing: { id: 'tank_testing', laborLabel: 'Underground Storage Tank Service', disposalLabel: 'Hazardous Waste Facility', laborDesc: 'UST testing, tank tightness testing, leak detection, cathodic protection testing', disposalDesc: 'Tank removal, disposal, soil remediation, groundwater monitoring' },
  trench_shoring: { id: 'trench_shoring', laborLabel: 'Shoring Contractor', disposalLabel: 'Steel & Lumber Recycling', laborDesc: 'Trench shoring, slide rail systems, hydraulic shores, trench boxes, excavation safety, CalOSHA compliance', disposalDesc: 'Shoring equipment decontamination, steel recycling, HDPE shoring disposal' },
  wind_infrastructure: { id: 'wind_infrastructure', laborLabel: 'Wind Energy Contractor', disposalLabel: 'Industrial Recycling Center', laborDesc: 'Wind turbine maintenance, gearbox testing, blade inspection, generator testing, electrical testing', disposalDesc: 'Turbine decommissioning, blade recycling, gearbox disposal, transformer recycling' },
  wind_energy: { id: 'wind_energy', laborLabel: 'Wind Energy Contractor', disposalLabel: 'Turbine & Blade Recycling', laborDesc: 'Wind turbine installation, maintenance, blade repair, tower climbing, GWO certified technicians', disposalDesc: 'Turbine decommissioning, blade recycling, gearbox disposal, composite material recycling' },
};

export function getVerticalLabel(id: string, pane: 'labor' | 'disposal'): string {
  const v = verticalMatrix[id];
  return pane === 'labor' ? v.laborLabel : v.disposalLabel;
}
