export interface VerticalMatrixEntry {
  id: string;
  laborLabel: string;
  disposalLabel: string;
  laborDesc: string;
  disposalDesc: string;
}

export const verticalMatrix: Record<string, VerticalMatrixEntry> = {
  asbestos_abatement: { id: 'asbestos_abatement', laborLabel: 'Asbestos Abatement Contractors', disposalLabel: 'Hazardous Asbestos Containment', laborDesc: 'Asbestos remediation, lead paint abatement, hazmat containment, air monitoring', disposalDesc: 'Regulated asbestos waste transport, permitted hazmat landfill disposal' },
  elevator_inspection: { id: 'elevator_inspection', laborLabel: 'Elevator Mechanics & Inspectors', disposalLabel: 'Elevator Modernization Scrap & Metal Recycling', laborDesc: 'Elevator safety inspection, certification, load testing, ASME compliance', disposalDesc: 'Elevator modernization, obsolete equipment removal' },
  generator_testing: { id: 'generator_testing', laborLabel: 'Load-Bank Testing Technicians', disposalLabel: 'Spent Battery, Oil, & Fuel Disposal', laborDesc: 'Generator load bank testing, NFPA 110 compliance, emergency power testing', disposalDesc: 'Generator decommissioning, fuel polishing waste disposal, battery recycling' },
  marine_construction: { id: 'marine_construction', laborLabel: 'Marine & Dredging Contractors', disposalLabel: 'Dredged Spoils & Marine Scrap Receiving', laborDesc: 'Pile driving, seawall construction, bulkhead installation, dredging, dock building', disposalDesc: 'Dredge spoils disposal, marine debris management, sheet piling removal' },
  hydro_excavation: { id: 'hydro_excavation', laborLabel: 'Hydro-Excavation & Vac Operators', disposalLabel: 'Wet Mud & Hydro-Vac Slurry Dumping', laborDesc: 'Hydro excavation, potholing, daylighting, utility exposure, non-destructive digging', disposalDesc: 'Spoils disposal, slurry containment, water management' },
  industrial_demolition: { id: 'industrial_demolition', laborLabel: 'Heavy Demolition & Structural Crews', disposalLabel: 'C&D Processing & Heavy Salvage Yards', laborDesc: 'Industrial demolition, concrete breaking, selective demolition, building implosion', disposalDesc: 'Demolition debris processing, concrete crushing, landfill disposal' },
  industrial_wastewater: { id: 'industrial_wastewater', laborLabel: 'Wastewater Plant Field Operators', disposalLabel: 'Liquid Industrial Waste & Effluent Intake', laborDesc: 'Industrial wastewater treatment, process water management, pH adjustment, filtration', disposalDesc: 'Treated effluent discharge, sludge dewatering, wastewater hauling' },
  medical_waste: { id: 'medical_waste', laborLabel: 'Biohazard Collection Techs', disposalLabel: 'Medical Incineration & Autoclave Facilities', laborDesc: 'Medical waste collection, biohazard cleanup, sharps disposal, clinical waste pickup', disposalDesc: 'Autoclave sterilization, regulated medical waste incineration, treatment' },
  slurry_processing: { id: 'slurry_processing', laborLabel: 'Slurry Wall & Drilling Mud Specialists', disposalLabel: 'Bentonite & Drilling Fluid Tipping Sites', laborDesc: 'Concrete cutting, core drilling, saw cutting, concrete grinding, demolition', disposalDesc: 'Slurry dewatering/recycling, washout collection, filtration, filter press operations' },
  stormwater_compliance: { id: 'stormwater_compliance', laborLabel: 'SWPPP Erosion Control Crews', disposalLabel: 'Sediment & Spent Filter Media Disposal', laborDesc: 'SWPPP development, stormwater inspections, compliance monitoring, erosion control', disposalDesc: 'Stormwater treatment, sediment basin cleaning, silt removal, erosion control installation' },
  tank_testing: { id: 'tank_testing', laborLabel: 'UST Tank Testers & Technicians', disposalLabel: 'Tank Bottom Sludge & Fuel Remediation', laborDesc: 'UST testing, tank tightness testing, leak detection, cathodic protection testing', disposalDesc: 'Tank removal, disposal, soil remediation, groundwater monitoring' },
  high_voltage_electrical: { id: 'high_voltage_electrical', laborLabel: 'Substation & Grid Linemen', disposalLabel: 'Transformer Oil (PCB) & Heavy Copper Salvage', laborDesc: 'High voltage testing, transformer maintenance, switchgear testing, cable testing, NFPA 70E compliance', disposalDesc: 'PCB transformer disposal, SF6 recycling, decommissioned equipment recycling' },
  trench_shoring: { id: 'trench_shoring', laborLabel: 'Shoring & Structural Support Crews', disposalLabel: 'Shoring Steel & Timber Lagging Reclamation', laborDesc: 'Trench shoring, slide rail systems, hydraulic shores, trench boxes, excavation safety, CalOSHA compliance', disposalDesc: 'Shoring equipment decontamination, steel recycling, HDPE shoring disposal' },
  sandblasting: { id: 'sandblasting', laborLabel: 'Blasting & Industrial Coating Painters', disposalLabel: 'Spent Abrasive Media & Grit Recycling', laborDesc: 'Abrasive blasting, sandblasting, surface preparation, industrial coating removal, lead paint abatement', disposalDesc: 'Spent abrasive disposal, hazardous media transport, EPA TCLP compliant disposal' },
  dewatering: { id: 'dewatering', laborLabel: 'Wellpoint & High-Volume Pump Techs', disposalLabel: 'Dewatering Discharge & Filtration Sites', laborDesc: 'Construction dewatering, wellpoint systems, bypass pumping, groundwater control, trench dewatering', disposalDesc: 'Sediment basin discharge, filtration treatment, NPDEs permitted outfall discharge' },
  hazardous_soil_remediation: { id: 'hazardous_soil_remediation', laborLabel: 'Hazmat Soil Remediation Operators', disposalLabel: 'Class I/II Landfills & Contaminated Dirt Tipping', laborDesc: 'Soil excavation, contaminated soil removal, site remediation, bio-remediation', disposalDesc: 'Hazmat soil transport, TSCA/RCRA permitted landfill disposal, thermal treatment' },
  fire_sprinklers: { id: 'fire_sprinklers', laborLabel: 'Fire Sprinkler Fitters & Installers', disposalLabel: 'Fire Retardant Flush & Pipe Reclamation', laborDesc: 'Fire sprinkler hydrostatic testing, flow testing, NFPA 25 inspection', disposalDesc: 'Sprinkler system decommissioning, obsolete component recycling' },
  hvac_industrial: { id: 'hvac_industrial', laborLabel: 'Industrial HVAC/R Field Technicians', disposalLabel: 'Refrigerant Recovery & Chiller Scrapping', laborDesc: 'HVAC test and balance, air balancing, TAB services, airflow measurement', disposalDesc: 'HVAC equipment disposal, refrigerant recovery, ductwork removal' },
  solar_infrastructure: { id: 'solar_infrastructure', laborLabel: 'Utility-Scale Solar PV Electricians', disposalLabel: 'Solar Panel Recycling & Photovoltaic E-Waste', laborDesc: 'Solar PV installation, commercial solar mounting, electrical integration, inverter commissioning', disposalDesc: 'Decommissioned panel recycling, inverter disposal, racking scrap metal recovery' },
  wind_infrastructure: { id: 'wind_infrastructure', laborLabel: 'Wind Turbine Field Technicians', disposalLabel: 'Blade Decommissioning & Shredding Facilities', laborDesc: 'Wind turbine maintenance, gearbox testing, blade inspection, generator testing, electrical testing', disposalDesc: 'Turbine decommissioning, blade recycling, gearbox disposal, transformer recycling' },
};

export function getVerticalLabel(id: string, pane: 'labor' | 'disposal'): string {
  const v = verticalMatrix[id];
  return pane === 'labor' ? v.laborLabel : v.disposalLabel;
}
