export interface MatrixNode {
  labor: string;
  disposal: string;
}

export const VERTICAL_META: Record<string, { laborLabel: string; disposalLabel: string; matrixNode: MatrixNode }> = {
  asbestos_abatement: { laborLabel: 'Asbestos Abatement Contractors', disposalLabel: 'Hazardous Asbestos Containment', matrixNode: { labor: 'Asbestos remediation, lead paint abatement, hazmat containment, air monitoring', disposal: 'Regulated asbestos waste transport, permitted hazmat landfill disposal' } },
  elevator_inspection: { laborLabel: 'Elevator Mechanics & Inspectors', disposalLabel: 'Elevator Modernization Scrap & Metal Recycling', matrixNode: { labor: 'Elevator safety inspection, certification, load testing, ASME compliance', disposal: 'Elevator modernization, obsolete equipment removal' } },
  generator_testing: { laborLabel: 'Load-Bank Testing Technicians', disposalLabel: 'Spent Battery, Oil, & Fuel Disposal', matrixNode: { labor: 'Generator load bank testing, NFPA 110 compliance, emergency power testing', disposal: 'Generator decommissioning, fuel polishing waste disposal, battery recycling' } },
  marine_construction: { laborLabel: 'Marine & Dredging Contractors', disposalLabel: 'Dredged Spoils & Marine Scrap Receiving', matrixNode: { labor: 'Pile driving, seawall construction, bulkhead installation, dredging, dock building', disposal: 'Dredge spoils disposal, marine debris management, sheet piling removal' } },
  hydro_excavation: { laborLabel: 'Hydro-Excavation & Vac Operators', disposalLabel: 'Wet Mud & Hydro-Vac Slurry Dumping', matrixNode: { labor: 'Hydro excavation, potholing, daylighting, utility exposure, non-destructive digging', disposal: 'Spoils disposal, slurry containment, water management' } },
  industrial_demolition: { laborLabel: 'Heavy Demolition & Structural Crews', disposalLabel: 'C&D Processing & Heavy Salvage Yards', matrixNode: { labor: 'Industrial demolition, concrete breaking, selective demolition, building implosion', disposal: 'Demolition debris processing, concrete crushing, landfill disposal' } },
  industrial_wastewater: { laborLabel: 'Wastewater Plant Field Operators', disposalLabel: 'Liquid Industrial Waste & Effluent Intake', matrixNode: { labor: 'Industrial wastewater treatment, process water management, pH adjustment, filtration', disposal: 'Treated effluent discharge, sludge dewatering, wastewater hauling' } },
  medical_waste: { laborLabel: 'Biohazard Collection Techs', disposalLabel: 'Medical Incineration & Autoclave Facilities', matrixNode: { labor: 'Medical waste collection, biohazard cleanup, sharps disposal, clinical waste pickup', disposal: 'Autoclave sterilization, regulated medical waste incineration, treatment' } },
  slurry_processing: { laborLabel: 'Slurry Wall & Drilling Mud Specialists', disposalLabel: 'Bentonite & Drilling Fluid Tipping Sites', matrixNode: { labor: 'Concrete cutting, core drilling, saw cutting, concrete grinding, demolition', disposal: 'Slurry dewatering/recycling, washout collection, filtration, filter press operations' } },
  stormwater_compliance: { laborLabel: 'SWPPP Erosion Control Crews', disposalLabel: 'Sediment & Spent Filter Media Disposal', matrixNode: { labor: 'SWPPP development, stormwater inspections, compliance monitoring, erosion control', disposal: 'Stormwater treatment, sediment basin cleaning, silt removal, erosion control installation' } },
  tank_testing: { laborLabel: 'UST Tank Testers & Technicians', disposalLabel: 'Tank Bottom Sludge & Fuel Remediation', matrixNode: { labor: 'UST testing, tank tightness testing, leak detection, cathodic protection testing', disposal: 'Tank removal, disposal, soil remediation, groundwater monitoring' } },
  high_voltage_electrical: { laborLabel: 'Substation & Grid Linemen', disposalLabel: 'Transformer Oil (PCB) & Heavy Copper Salvage', matrixNode: { labor: 'High voltage testing, transformer maintenance, switchgear testing, cable testing, NFPA 70E compliance', disposal: 'PCB transformer disposal, SF6 recycling, decommissioned equipment recycling' } },
  trench_shoring: { laborLabel: 'Shoring & Structural Support Crews', disposalLabel: 'Shoring Steel & Timber Lagging Reclamation', matrixNode: { labor: 'Trench shoring, slide rail systems, hydraulic shores, trench boxes, excavation safety, CalOSHA compliance', disposal: 'Shoring equipment decontamination, steel recycling, HDPE shoring disposal' } },
  sandblasting: { laborLabel: 'Blasting & Industrial Coating Painters', disposalLabel: 'Spent Abrasive Media & Grit Recycling', matrixNode: { labor: 'Abrasive blasting, sandblasting, surface preparation, industrial coating removal, lead paint abatement', disposal: 'Spent abrasive disposal, hazardous media transport, EPA TCLP compliant disposal' } },
  dewatering: { laborLabel: 'Wellpoint & High-Volume Pump Techs', disposalLabel: 'Dewatering Discharge & Filtration Sites', matrixNode: { labor: 'Construction dewatering, wellpoint systems, bypass pumping, groundwater control, trench dewatering', disposal: 'Sediment basin discharge, filtration treatment, NPDEs permitted outfall discharge' } },
  hazardous_soil_remediation: { laborLabel: 'Hazmat Soil Remediation Operators', disposalLabel: 'Class I/II Landfills & Contaminated Dirt Tipping', matrixNode: { labor: 'Soil excavation, contaminated soil removal, site remediation, bio-remediation', disposal: 'Hazmat soil transport, TSCA/RCRA permitted landfill disposal, thermal treatment' } },
  fire_sprinklers: { laborLabel: 'Fire Sprinkler Fitters & Installers', disposalLabel: 'Fire Retardant Flush & Pipe Reclamation', matrixNode: { labor: 'Fire sprinkler hydrostatic testing, flow testing, NFPA 25 inspection', disposal: 'Sprinkler system decommissioning, obsolete component recycling' } },
  hvac_industrial: { laborLabel: 'Industrial HVAC/R Field Technicians', disposalLabel: 'Refrigerant Recovery & Chiller Scrapping', matrixNode: { labor: 'HVAC test and balance, air balancing, TAB services, airflow measurement', disposal: 'HVAC equipment disposal, refrigerant recovery, ductwork removal' } },
  solar_infrastructure: { laborLabel: 'Utility-Scale Solar PV Electricians', disposalLabel: 'Solar Panel Recycling & Photovoltaic E-Waste', matrixNode: { labor: 'Solar PV installation, commercial solar mounting, electrical integration, inverter commissioning', disposal: 'Decommissioned panel recycling, inverter disposal, racking scrap metal recovery' } },
  wind_infrastructure: { laborLabel: 'Wind Turbine Field Technicians', disposalLabel: 'Blade Decommissioning & Shredding Facilities', matrixNode: { labor: 'Wind turbine maintenance, gearbox testing, blade inspection, generator testing, electrical testing', disposal: 'Turbine decommissioning, blade recycling, gearbox disposal, transformer recycling' } },
};
