// Legacy: CA FOG grease trap seed records — preserved for future regulatory scraper
export const CA_FOG_SEED_RECORDS = [
  {
    id: 'reg-ca-fog-darling',
    companyName: 'Darling Ingredients Inc.',
    address: '251 Oconnor Ridge Blvd',
    city: 'Irving',
    state: 'CA',
    zip: '75038',
    latitude: 33.918,
    longitude: -117.928,
    website: 'darlingii.com',
    phone: '800-600-1788',
    notes: 'CA FOG Processor #FOG-2022-0841. Grease trap waste collection, grease recycling, rendering. Permitted grease hauler and processor.',
    source: 'regulatory_permit',
    permits: [{ agency: 'California Department of Public Health', permitType: 'FOG Processor', permitNumber: 'FOG-2022-0841', status: 'Active' }],
  },
  {
    id: 'reg-ca-fog-baker',
    companyName: 'Baker Commodities Inc.',
    address: '4020 Bandini Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90058',
    latitude: 33.998,
    longitude: -118.206,
    website: 'bakercommodities.com',
    phone: '323-268-2801',
    notes: 'CA FOG Processor #FOG-2019-0634. Grease trap pumping, grease recycling, rendering services. Permitted grease hauler and processor.',
    source: 'regulatory_permit',
    permits: [{ agency: 'California Department of Public Health', permitType: 'FOG Processor', permitNumber: 'FOG-2019-0634', status: 'Active' }],
  },
  {
    id: 'reg-ca-fog-mission',
    companyName: 'Mission Kleen Supply LLC',
    address: '4220 East La Palma Ave',
    city: 'Anaheim',
    state: 'CA',
    zip: '92807',
    latitude: 33.861,
    longitude: -117.834,
    website: 'missionkleen.com',
    phone: '714-772-2284',
    notes: 'CA FOG Grease Hauler. Grease trap pumping, interceptor cleaning, grease recycling.',
    source: 'regulatory_permit',
    permits: [{ agency: 'Orange County Environmental Health', permitType: 'FOG Grease Hauler', permitNumber: 'OC-FOG-2023-0041', status: 'Active' }],
  },
  {
    id: 'reg-ca-fog-rwmartin',
    companyName: 'R.W. Martin Inc.',
    address: '3069 Alhambra Dr',
    city: 'Cameron Park',
    state: 'CA',
    zip: '95682',
    latitude: 38.660,
    longitude: -120.999,
    phone: '530-676-2325',
    notes: 'CA FOG Grease Hauler. Grease trap pumping, portable toilet rental, septic services. Permitted grease hauler in Northern California.',
    source: 'regulatory_permit',
    permits: [{ agency: 'El Dorado County Environmental Health', permitType: 'FOG Grease Hauler', permitNumber: 'ED-FOG-2024-0012', status: 'Active' }],
  },
  {
    id: 'reg-ca-fog-bsd',
    companyName: 'B-S-D Enterprises Inc.',
    address: '2200 E 49th St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90058',
    latitude: 33.998,
    longitude: -118.242,
    website: 'bsdenterprises.com',
    phone: '323-231-0460',
    notes: 'CA FOG Grease Hauler #FOG-2020-1249. Grease trap pumping, grease interceptor cleaning, used cooking oil collection.',
    source: 'regulatory_permit',
    permits: [{ agency: 'Los Angeles County Environmental Health', permitType: 'FOG Grease Hauler', permitNumber: 'FOG-2020-1249', status: 'Active' }],
  },
];
